name: simple_dart_loadable_object_table
description: Loadable Wrapper for ObjectTable Component
version: 0.0.1
repository: https://github.com/simple-dart/loadable_object_table
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_load_indicator: ^0.0.1
  simple_dart_object_table: ^0.1.0
